# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: peer_doc_review
  pool: 5
  username: peer_doc_review
  password: peer_doc_review

test:
  adapter: postgresql
  encoding: unicode
  database: peer_doc_review_test
  pool: 5
  username: peer_doc_review
  password: peer_doc_review

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
